/**
 * Unit tests for Markdown documentation generator
 * Tests comprehensive documentation generation from scanned configuration
 */

import { describe, it, expect } from 'vitest';
import { generateMarkdown } from '../../../src/core/generators/docs/markdown.js';
import type { AgentScopeConfig, Agent, Skill, Hook, Command, McpServer } from '../../../src/core/model/types.js';

// Helper to create a minimal config
function createConfig(overrides: Partial<AgentScopeConfig> = {}): AgentScopeConfig {
  return {
    agents: [],
    skills: [],
    hooks: [],
    commands: [],
    mcpServers: [],
    plugins: [],
    permissions: {
      allowCount: 0,
      denyCount: 0,
      askCount: 0,
      rules: [],
    },
    metadata: {
      scannedAt: new Date('2024-01-15T10:00:00Z'),
      rootPath: '/test/project',
      version: '1.0.0',
      duration: 150,
      filesScanned: 25,
      errors: [],
    },
    ...overrides,
  };
}

// Helper to create an agent
function createAgent(name: string, overrides: Partial<Agent> = {}): Agent {
  return {
    name,
    path: `.claude/agents/${name}.md`,
    description: `Description for ${name}`,
    ...overrides,
  };
}

// Helper to create a skill
function createSkill(name: string, overrides: Partial<Skill> = {}): Skill {
  return {
    name,
    path: `.claude/skills/${name}/SKILL.md`,
    description: `Description for ${name}`,
    ...overrides,
  };
}

// Helper to create a hook
function createHook(event: Hook['event'], overrides: Partial<Hook> = {}): Hook {
  return {
    event,
    path: '.claude/settings.json',
    ...overrides,
  };
}

// Helper to create a command
function createCommand(name: string, overrides: Partial<Command> = {}): Command {
  return {
    name,
    description: `Description for ${name}`,
    ...overrides,
  };
}

// Helper to create an MCP server
function createServer(name: string, overrides: Partial<McpServer> = {}): McpServer {
  return {
    name,
    command: 'node',
    args: ['server.js'],
    ...overrides,
  };
}

describe('generateMarkdown', () => {
  describe('basic structure', () => {
    it('should generate a valid markdown document', async () => {
      const config = createConfig();
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('# ');
      expect(result).toContain('## ');
    });

    it('should include generation metadata', async () => {
      const config = createConfig();
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('Generated by AgentScope');
      expect(result).toContain('v1.0.0');
      expect(result).toContain('Scanned:');
    });

    it('should use custom title when provided', async () => {
      const config = createConfig();
      const result = await generateMarkdown(config, { title: 'Custom Title' });

      expect(result).toContain('# Custom Title');
    });

    it('should use default title when not specified', async () => {
      const config = createConfig();
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('# Agent Architecture Documentation');
    });
  });

  describe('table of contents', () => {
    it('should include table of contents by default', async () => {
      const config = createConfig({
        agents: [createAgent('test')],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## Table of Contents');
      expect(result).toContain('- [Overview](#overview)');
      expect(result).toContain('- [Agents](#agents-comparison)');
    });

    it('should not include TOC when option is false', async () => {
      const config = createConfig();
      const result = await generateMarkdown(config, { includeToc: false });

      expect(result).not.toContain('## Table of Contents');
    });

    it('should only include links to existing sections', async () => {
      const config = createConfig({
        agents: [createAgent('test')],
        // No skills, hooks, commands, or MCP servers
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('- [Agents](#agents-comparison)');
      expect(result).not.toContain('- [Skills](#skills)');
      expect(result).not.toContain('- [Commands](#commands)');
    });
  });

  describe('overview section', () => {
    it('should include component counts table', async () => {
      const config = createConfig({
        agents: [createAgent('a1'), createAgent('a2')],
        skills: [createSkill('s1')],
        hooks: [createHook('PreToolUse')],
        commands: [createCommand('/cmd')],
        mcpServers: [createServer('server')],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## Overview');
      expect(result).toContain('| Component | Count |');
      expect(result).toContain('| Agents | 2 |');
      expect(result).toContain('| Skills | 1 |');
      expect(result).toContain('| Hooks | 1 |');
      expect(result).toContain('| Commands | 1 |');
      expect(result).toContain('| MCP Servers | 1 |');
    });

    it('should show agent type breakdown', async () => {
      const config = createConfig({
        agents: [
          createAgent('coord', { type: 'coordinator' }),
          createAgent('worker1', { type: 'worker' }),
          createAgent('worker2', { type: 'worker' }),
          createAgent('reviewer', { type: 'reviewer' }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('### Agent Types');
      expect(result).toContain('Coordinator');
      expect(result).toContain('Worker');
      expect(result).toContain('Reviewer');
    });

    it('should show MCP server status breakdown', async () => {
      const config = createConfig({
        mcpServers: [
          createServer('enabled', { disabled: false }),
          createServer('disabled', { disabled: true }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('### MCP Server Status');
      expect(result).toContain('**Enabled**: 1');
      expect(result).toContain('**Disabled**: 1');
    });
  });

  describe('agents section', () => {
    it('should generate detailed agent documentation', async () => {
      const config = createConfig({
        agents: [
          createAgent('test-agent', {
            type: 'worker',
            description: 'A test agent',
            tools: ['read', 'write'],
            delegatesTo: ['sub-agent'],
          }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## Agents Comparison');
      expect(result).toContain('**test-agent**');
      expect(result).toContain('**Type**: `Worker`');
      expect(result).toContain('A test agent');
      expect(result).toContain('**Tools**:');
      expect(result).toContain('`read`');
      expect(result).toContain('**Delegates to**:');
      expect(result).toContain('sub-agent');
    });

    it('should sort agents by type then name', async () => {
      const config = createConfig({
        agents: [
          createAgent('z-worker', { type: 'worker' }),
          createAgent('a-coordinator', { type: 'coordinator' }),
          createAgent('b-worker', { type: 'worker' }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      // Coordinator should come before workers
      const coordIndex = result.indexOf('### a-coordinator');
      const worker1Index = result.indexOf('### b-worker');
      const worker2Index = result.indexOf('### z-worker');

      expect(coordIndex).toBeLessThan(worker1Index);
      expect(worker1Index).toBeLessThan(worker2Index);
    });

    it('should show agent source path', async () => {
      const config = createConfig({
        agents: [
          createAgent('test', { path: '.claude/agents/core/test.md' }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('**Defined in**: `.claude/agents/core/test.md`');
    });
  });

  describe('skills section', () => {
    it('should generate skills table and details', async () => {
      const config = createConfig({
        skills: [
          createSkill('code-review', {
            description: 'Code review skill',
            triggers: ['review', 'pr'],
            dependencies: ['testing'],
            enabled: true,
          }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## Skills');
      expect(result).toContain('| Skill | Description | Triggers | Status |');
      expect(result).toContain('code-review');
      expect(result).toContain('### code-review');
      expect(result).toContain('**Triggers**:');
      expect(result).toContain('`review`');
      expect(result).toContain('**Dependencies**:');
      expect(result).toContain('testing');
    });

    it('should show disabled status for disabled skills', async () => {
      const config = createConfig({
        skills: [
          createSkill('disabled-skill', { enabled: false }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('Disabled');
    });
  });

  describe('hooks section', () => {
    it('should generate hooks table', async () => {
      const config = createConfig({
        hooks: [
          createHook('PreToolUse', {
            command: 'echo "pre"',
            timeout: 5000,
            enabled: true,
          }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## Hooks');
      expect(result).toContain('| Event | Command | Timeout | Status |');
      expect(result).toContain('**PreToolUse**');
      expect(result).toContain('5000ms');
    });

    it('should group hooks by event type', async () => {
      const config = createConfig({
        hooks: [
          createHook('PreToolUse', { command: 'echo pre' }),
          createHook('PostToolUse', { command: 'echo post' }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('### Hook Events');
      expect(result).toContain('#### PreToolUse');
      expect(result).toContain('#### PostToolUse');
    });

    it('should include hook event descriptions', async () => {
      const config = createConfig({
        hooks: [
          createHook('PreToolUse'),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('Triggered before a tool is executed');
    });

    it('should show command code blocks', async () => {
      const config = createConfig({
        hooks: [
          createHook('PreToolUse', { command: 'npm run lint' }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('```bash');
      expect(result).toContain('npm run lint');
    });
  });

  describe('commands section', () => {
    it('should generate commands table and details', async () => {
      const config = createConfig({
        commands: [
          createCommand('/deploy', {
            description: 'Deploy to production',
            allowedTools: ['bash', 'git'],
            prompt: 'Deploy the application',
          }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## Commands');
      expect(result).toContain('| Command | Description |');
      expect(result).toContain('`/deploy`');
      expect(result).toContain('### /deploy');
      expect(result).toContain('**Allowed Tools**:');
      expect(result).toContain('`bash`');
      expect(result).toContain('**Prompt**:');
    });

    it('should show disallowed tools', async () => {
      const config = createConfig({
        commands: [
          createCommand('/safe', { disallowedTools: ['rm', 'del'] }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('**Disallowed Tools**:');
      expect(result).toContain('`rm`');
    });
  });

  describe('MCP servers section', () => {
    it('should generate MCP servers table and details', async () => {
      const config = createConfig({
        mcpServers: [
          createServer('github', {
            command: 'npx',
            args: ['@github/mcp-server'],
            type: 'stdio',
            env: { TOKEN: 'secret' },
            tools: ['read', 'write'],
          }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## MCP Servers');
      expect(result).toContain('| Server | Command | Type | Status |');
      expect(result).toContain('**github**');
      expect(result).toContain('### github');
      expect(result).toContain('**Command**:');
      expect(result).toContain('npx @github/mcp-server');
      expect(result).toContain('**Provides Tools**:');
    });

    it('should mask sensitive environment variables', async () => {
      const config = createConfig({
        mcpServers: [
          createServer('test', {
            env: {
              GITHUB_TOKEN: 'actual-secret-token',
              API_KEY: 'another-secret',
              NORMAL_VAR: 'visible-value',
            },
          }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('***masked***');
      expect(result).not.toContain('actual-secret-token');
      expect(result).not.toContain('another-secret');
      expect(result).toContain('visible-value');
    });

    it('should show disabled status', async () => {
      const config = createConfig({
        mcpServers: [
          createServer('disabled', { disabled: true }),
        ],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('Disabled');
    });
  });

  describe('diagrams section', () => {
    it('should include diagrams by default', async () => {
      const config = createConfig({
        agents: [createAgent('test')],
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## Diagrams');
      expect(result).toContain('### Component Map');
      expect(result).toContain('### Agent Hierarchy');
      expect(result).toContain('### Dataflow');
      expect(result).toContain('```mermaid');
    });

    it('should not include diagrams when option is false', async () => {
      const config = createConfig({
        agents: [createAgent('test')],
      });
      const result = await generateMarkdown(config, { includeDiagrams: false });

      expect(result).not.toContain('## Diagrams');
      expect(result).not.toContain('```mermaid');
    });
  });

  describe('metadata section', () => {
    it('should include scan metadata by default', async () => {
      const config = createConfig();
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('## Scan Metadata');
      expect(result).toContain('| Property | Value |');
      expect(result).toContain('Scanned At');
      expect(result).toContain('Root Path');
      expect(result).toContain('/test/project');
      expect(result).toContain('Files Scanned');
      expect(result).toContain('25');
      expect(result).toContain('Duration');
      expect(result).toContain('150ms');
    });

    it('should not include metadata when option is false', async () => {
      const config = createConfig();
      const result = await generateMarkdown(config, { includeMetadata: false });

      expect(result).not.toContain('## Scan Metadata');
    });

    it('should show scan warnings if any', async () => {
      const config = createConfig({
        metadata: {
          scannedAt: new Date(),
          rootPath: '/test',
          version: '1.0.0',
          duration: 100,
          filesScanned: 10,
          errors: [
            { severity: 'warning', code: 'TEST_WARN', message: 'Test warning' },
            { severity: 'info', code: 'TEST_INFO', message: 'Test info', file: 'test.md' },
          ],
        },
      });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).toContain('### Scan Warnings');
      expect(result).toContain('TEST_WARN');
      expect(result).toContain('Test warning');
    });
  });

  describe('empty sections handling', () => {
    it('should not include agents section when empty', async () => {
      const config = createConfig({ agents: [] });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).not.toContain('## Agents');
    });

    it('should not include skills section when empty', async () => {
      const config = createConfig({ skills: [] });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).not.toContain('## Skills');
    });

    it('should not include hooks section when empty', async () => {
      const config = createConfig({ hooks: [] });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).not.toContain('## Hooks');
    });

    it('should not include commands section when empty', async () => {
      const config = createConfig({ commands: [] });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).not.toContain('## Commands');
    });

    it('should not include MCP servers section when empty', async () => {
      const config = createConfig({ mcpServers: [] });
      const result = await generateMarkdown(config, { useEnhancedFormatters: false });

      expect(result).not.toContain('## MCP Servers');
    });
  });
});

describe('generateMarkdown - Snapshot Tests', () => {
  it('should match snapshot for minimal config', async () => {
    const config = createConfig({
      agents: [createAgent('simple-agent', { type: 'worker' })],
    });

    const result = await generateMarkdown(config, {
      includeDiagrams: false,
      includeMetadata: false,
      includeToc: false,
      title: 'Minimal Documentation',
    });

    expect(result).toMatchSnapshot();
  });

  it('should match snapshot for full config', async () => {
    const config = createConfig({
      agents: [
        createAgent('coordinator', {
          type: 'coordinator',
          delegatesTo: ['worker'],
          tools: ['github'],
        }),
        createAgent('worker', { type: 'worker' }),
      ],
      skills: [createSkill('code-review', { triggers: ['review'] })],
      hooks: [createHook('PreToolUse', { command: 'npm run lint' })],
      commands: [createCommand('/deploy')],
      mcpServers: [createServer('github')],
    });

    const result = await generateMarkdown(config, {
      includeDiagrams: false, // Exclude for stable snapshot
      title: 'Full Documentation',
    });

    expect(result).toMatchSnapshot();
  });
});
