/**
 * Comprehensive error code definitions for Claude Flow
 * Follows pattern: DOMAIN_SEQUENCE
 * Example: MEMORY_001, SECURITY_002, AGENT_003
 */

export const ERROR_CODES = {
  // Validation Errors (VAL_XXX)
  VALIDATION_001: 'VALIDATION_001',
  VALIDATION_002: 'VALIDATION_002',
  VALIDATION_003: 'VALIDATION_003',
  VALIDATION_MISSING_REQUIRED: 'VALIDATION_001',
  VALIDATION_INVALID_TYPE: 'VALIDATION_002',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_003',

  // Security Errors (SEC_XXX)
  SECURITY_001: 'SECURITY_001',
  SECURITY_002: 'SECURITY_002',
  SECURITY_003: 'SECURITY_003',
  SECURITY_004: 'SECURITY_004',
  SECURITY_INJECTION_DETECTED: 'SECURITY_001',
  SECURITY_UNAUTHORIZED: 'SECURITY_002',
  SECURITY_FORBIDDEN: 'SECURITY_003',
  SECURITY_INVALID_TOKEN: 'SECURITY_004',

  // Memory Errors (MEM_XXX)
  MEMORY_001: 'MEMORY_001',
  MEMORY_002: 'MEMORY_002',
  MEMORY_003: 'MEMORY_003',
  MEMORY_004: 'MEMORY_004',
  MEMORY_OUT_OF_SPACE: 'MEMORY_001',
  MEMORY_NOT_FOUND: 'MEMORY_002',
  MEMORY_OPERATION_FAILED: 'MEMORY_003',
  MEMORY_CORRUPTED: 'MEMORY_004',

  // Agent Errors (AGT_XXX)
  AGENT_001: 'AGENT_001',
  AGENT_002: 'AGENT_002',
  AGENT_003: 'AGENT_003',
  AGENT_004: 'AGENT_004',
  AGENT_NOT_FOUND: 'AGENT_001',
  AGENT_EXECUTION_FAILED: 'AGENT_002',
  AGENT_TIMEOUT: 'AGENT_003',
  AGENT_INVALID_STATE: 'AGENT_004',

  // Configuration Errors (CFG_XXX)
  CONFIG_001: 'CONFIG_001',
  CONFIG_002: 'CONFIG_002',
  CONFIG_003: 'CONFIG_003',
  CONFIG_MISSING: 'CONFIG_001',
  CONFIG_INVALID: 'CONFIG_002',
  CONFIG_MERGE_FAILED: 'CONFIG_003',

  // Network Errors (NET_XXX)
  NETWORK_001: 'NETWORK_001',
  NETWORK_002: 'NETWORK_002',
  NETWORK_003: 'NETWORK_003',
  NETWORK_004: 'NETWORK_004',
  NETWORK_TIMEOUT: 'NETWORK_001',
  NETWORK_CONNECTION_REFUSED: 'NETWORK_002',
  NETWORK_INVALID_RESPONSE: 'NETWORK_003',
  NETWORK_DNS_FAILED: 'NETWORK_004',

  // File System Errors (FS_XXX)
  FS_001: 'FS_001',
  FS_002: 'FS_002',
  FS_003: 'FS_003',
  FS_FILE_NOT_FOUND: 'FS_001',
  FS_PERMISSION_DENIED: 'FS_002',
  FS_WRITE_FAILED: 'FS_003',

  // Database Errors (DB_XXX)
  DB_001: 'DB_001',
  DB_002: 'DB_002',
  DB_003: 'DB_003',
  DB_CONNECTION_FAILED: 'DB_001',
  DB_QUERY_FAILED: 'DB_002',
  DB_TRANSACTION_FAILED: 'DB_003',

  // Internal Errors (INT_XXX)
  INTERNAL_001: 'INTERNAL_001',
  INTERNAL_002: 'INTERNAL_002',
  INTERNAL_UNKNOWN: 'INTERNAL_001',
  INTERNAL_NOT_IMPLEMENTED: 'INTERNAL_002',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Error severity levels
 */
export enum ErrorSeverity {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

/**
 * Error categories for classification
 */
export enum ErrorCategory {
  VALIDATION = 'validation',
  SECURITY = 'security',
  MEMORY = 'memory',
  AGENT = 'agent',
  CONFIG = 'config',
  NETWORK = 'network',
  FILE_SYSTEM = 'file_system',
  DATABASE = 'database',
  INTERNAL = 'internal',
}
