/**
 * Markdown Documentation Generator
 * Generates comprehensive documentation from the scanned configuration
 */

import type { AgentScopeConfig, Agent, Skill, Hook, Command, McpServer, DiagramOptions } from '../../model/types.js';
import { generateComponentMap, type ComponentMapOptions } from '../diagrams/component-map.js';
import { generateHierarchy, type HierarchyOptions } from '../diagrams/hierarchy.js';
import { generateDataflow } from '../diagrams/dataflow.js';

export interface MarkdownOptions {
  /** Include diagrams in documentation */
  includeDiagrams?: boolean;
  /** Include scan metadata */
  includeMetadata?: boolean;
  /** Custom title */
  title?: string;
  /** Include table of contents */
  includeToc?: boolean;
  /** Diagram generation options */
  diagramOptions?: DiagramOptions;
}

/**
 * Generate comprehensive markdown documentation
 */
export function generateMarkdown(
  config: AgentScopeConfig,
  options: MarkdownOptions = {}
): string {
  const {
    includeDiagrams = true,
    includeMetadata = true,
    title = 'Agent Architecture Documentation',
    includeToc = true,
    diagramOptions = {},
  } = options;

  const sections: string[] = [];

  // Header
  sections.push(`# ${title}`);
  sections.push('');
  sections.push(`> Generated by AgentScope v${config.metadata.version}`);
  sections.push(`> Scanned: ${config.metadata.scannedAt.toISOString()}`);
  sections.push('');

  // Table of Contents
  if (includeToc) {
    sections.push('## Table of Contents');
    sections.push('');
    sections.push('- [Overview](#overview)');
    if (config.agents.length > 0) sections.push('- [Agents](#agents)');
    if (config.skills.length > 0) sections.push('- [Skills](#skills)');
    if (config.hooks.length > 0) sections.push('- [Hooks](#hooks)');
    if (config.commands.length > 0) sections.push('- [Commands](#commands)');
    if (config.mcpServers.length > 0) sections.push('- [MCP Servers](#mcp-servers)');
    if (includeDiagrams) sections.push('- [Diagrams](#diagrams)');
    if (includeMetadata) sections.push('- [Scan Metadata](#scan-metadata)');
    sections.push('');
  }

  // Overview
  sections.push('## Overview');
  sections.push('');
  sections.push(generateOverview(config));
  sections.push('');

  // Agents
  if (config.agents.length > 0) {
    sections.push('## Agents');
    sections.push('');
    sections.push(generateAgentsSection(config.agents));
    sections.push('');
  }

  // Skills
  if (config.skills.length > 0) {
    sections.push('## Skills');
    sections.push('');
    sections.push(generateSkillsSection(config.skills));
    sections.push('');
  }

  // Hooks
  if (config.hooks.length > 0) {
    sections.push('## Hooks');
    sections.push('');
    sections.push(generateHooksSection(config.hooks));
    sections.push('');
  }

  // Commands
  if (config.commands.length > 0) {
    sections.push('## Commands');
    sections.push('');
    sections.push(generateCommandsSection(config.commands));
    sections.push('');
  }

  // MCP Servers
  if (config.mcpServers.length > 0) {
    sections.push('## MCP Servers');
    sections.push('');
    sections.push(generateMcpSection(config.mcpServers));
    sections.push('');
  }

  // Diagrams
  if (includeDiagrams) {
    // Build diagram options from user preferences
    const componentMapOpts: ComponentMapOptions = {
      title: 'Component Map',
      level: diagramOptions.level ?? 'category',
      compact: diagramOptions.compact ?? false,
      categories: diagramOptions.categories as ComponentMapOptions['categories'],
      types: diagramOptions.types,
      pattern: diagramOptions.pattern,
      maxPerCategory: diagramOptions.maxPerCategory ?? 20,
    };

    const hierarchyOpts: HierarchyOptions = {
      title: 'Agent Hierarchy',
      level: diagramOptions.level ?? 'category',
      compact: diagramOptions.compact ?? false,
      categories: diagramOptions.categories as HierarchyOptions['categories'],
      types: diagramOptions.types,
      pattern: diagramOptions.pattern,
      maxPerCategory: diagramOptions.maxPerCategory ?? 15,
    };

    sections.push('## Diagrams');
    sections.push('');
    sections.push('### Component Map');
    sections.push('');
    sections.push(generateComponentMap(config, componentMapOpts));
    sections.push('');
    sections.push('### Agent Hierarchy');
    sections.push('');
    sections.push(generateHierarchy(config, hierarchyOpts));
    sections.push('');
    sections.push('### Dataflow');
    sections.push('');
    sections.push(generateDataflow(config, { title: 'Dataflow' }));
    sections.push('');
  }

  // Metadata
  if (includeMetadata) {
    sections.push('## Scan Metadata');
    sections.push('');
    sections.push(generateMetadataSection(config));
    sections.push('');
  }

  return sections.join('\n');
}

/**
 * Generate overview section
 */
function generateOverview(config: AgentScopeConfig): string {
  const lines: string[] = [];

  lines.push('| Component | Count |');
  lines.push('|-----------|-------|');
  lines.push(`| Agents | ${config.agents.length} |`);
  lines.push(`| Skills | ${config.skills.length} |`);
  lines.push(`| Hooks | ${config.hooks.length} |`);
  lines.push(`| Commands | ${config.commands.length} |`);
  lines.push(`| MCP Servers | ${config.mcpServers.length} |`);

  // Add breakdown by type
  if (config.agents.length > 0) {
    lines.push('');
    lines.push('### Agent Types');
    lines.push('');

    const typeCount = countAgentTypes(config.agents);
    for (const [type, count] of Object.entries(typeCount)) {
      if (count > 0) {
        lines.push(`- **${capitalize(type)}**: ${count}`);
      }
    }
  }

  if (config.mcpServers.length > 0) {
    const enabled = config.mcpServers.filter(s => !s.disabled).length;
    const disabled = config.mcpServers.length - enabled;
    lines.push('');
    lines.push('### MCP Server Status');
    lines.push('');
    lines.push(`- **Enabled**: ${enabled}`);
    lines.push(`- **Disabled**: ${disabled}`);
  }

  return lines.join('\n');
}

/**
 * Generate agents section
 */
function generateAgentsSection(agents: Agent[]): string {
  const lines: string[] = [];

  // Sort agents by type, then name
  const sortedAgents = [...agents].sort((a, b) => {
    const typeOrder = ['coordinator', 'specialist', 'reviewer', 'worker', 'custom'];
    const typeA = typeOrder.indexOf(a.type ?? 'worker');
    const typeB = typeOrder.indexOf(b.type ?? 'worker');
    if (typeA !== typeB) return typeA - typeB;
    return a.name.localeCompare(b.name);
  });

  for (const agent of sortedAgents) {
    lines.push(`### ${agent.name}`);
    lines.push('');

    // Type badge
    const typeBadge = getTypeBadge(agent.type);
    lines.push(`**Type**: ${typeBadge}`);
    lines.push('');

    // Description
    if (agent.description) {
      lines.push(agent.description);
      lines.push('');
    }

    // Path
    lines.push(`**Defined in**: \`${agent.path}\``);
    lines.push('');

    // Tools
    if (agent.tools && agent.tools.length > 0) {
      lines.push('**Tools**:');
      for (const tool of agent.tools) {
        lines.push(`- \`${tool}\``);
      }
      lines.push('');
    }

    // Delegation
    if (agent.delegatesTo && agent.delegatesTo.length > 0) {
      lines.push('**Delegates to**:');
      for (const target of agent.delegatesTo) {
        lines.push(`- ${target}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate skills section
 */
function generateSkillsSection(skills: Skill[]): string {
  const lines: string[] = [];

  lines.push('| Skill | Description | Triggers | Status |');
  lines.push('|-------|-------------|----------|--------|');

  for (const skill of skills) {
    const triggers = skill.triggers?.join(', ') ?? '-';
    const status = skill.enabled === false ? 'Disabled' : 'Enabled';
    const description = skill.description ?? '-';
    lines.push(`| **${skill.name}** | ${truncate(description, 50)} | ${triggers} | ${status} |`);
  }

  // Detailed sections
  lines.push('');
  for (const skill of skills) {
    lines.push(`### ${skill.name}`);
    lines.push('');

    if (skill.description) {
      lines.push(skill.description);
      lines.push('');
    }

    lines.push(`**Path**: \`${skill.path}\``);
    lines.push('');

    if (skill.triggers && skill.triggers.length > 0) {
      lines.push('**Triggers**:');
      for (const trigger of skill.triggers) {
        lines.push(`- \`${trigger}\``);
      }
      lines.push('');
    }

    if (skill.dependencies && skill.dependencies.length > 0) {
      lines.push('**Dependencies**:');
      for (const dep of skill.dependencies) {
        lines.push(`- ${dep}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate hooks section
 */
function generateHooksSection(hooks: Hook[]): string {
  const lines: string[] = [];

  // Group by event
  const hooksByEvent = new Map<string, Hook[]>();
  for (const hook of hooks) {
    const existing = hooksByEvent.get(hook.event) ?? [];
    existing.push(hook);
    hooksByEvent.set(hook.event, existing);
  }

  lines.push('| Event | Command | Timeout | Status |');
  lines.push('|-------|---------|---------|--------|');

  for (const hook of hooks) {
    const command = hook.command ? `\`${truncate(hook.command, 40)}\`` : '-';
    const timeout = hook.timeout ? `${hook.timeout}ms` : 'Default';
    const status = hook.enabled === false ? 'Disabled' : 'Enabled';
    lines.push(`| **${hook.event}** | ${command} | ${timeout} | ${status} |`);
  }

  lines.push('');
  lines.push('### Hook Events');
  lines.push('');

  for (const [event, eventHooks] of hooksByEvent) {
    lines.push(`#### ${event}`);
    lines.push('');
    lines.push(getHookEventDescription(event));
    lines.push('');

    for (const hook of eventHooks) {
      if (hook.command) {
        lines.push('```bash');
        lines.push(hook.command);
        lines.push('```');
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

/**
 * Generate commands section
 */
function generateCommandsSection(commands: Command[]): string {
  const lines: string[] = [];

  lines.push('| Command | Description |');
  lines.push('|---------|-------------|');

  for (const command of commands) {
    const description = command.description ?? '-';
    lines.push(`| \`${command.name}\` | ${truncate(description, 60)} |`);
  }

  lines.push('');

  for (const command of commands) {
    lines.push(`### ${command.name}`);
    lines.push('');

    if (command.description) {
      lines.push(command.description);
      lines.push('');
    }

    if (command.allowedTools && command.allowedTools.length > 0) {
      lines.push('**Allowed Tools**:');
      for (const tool of command.allowedTools) {
        lines.push(`- \`${tool}\``);
      }
      lines.push('');
    }

    if (command.disallowedTools && command.disallowedTools.length > 0) {
      lines.push('**Disallowed Tools**:');
      for (const tool of command.disallowedTools) {
        lines.push(`- \`${tool}\``);
      }
      lines.push('');
    }

    if (command.prompt) {
      lines.push('**Prompt**:');
      lines.push('');
      lines.push('```');
      lines.push(truncate(command.prompt, 500));
      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate MCP servers section
 */
function generateMcpSection(servers: McpServer[]): string {
  const lines: string[] = [];

  lines.push('| Server | Command | Type | Status |');
  lines.push('|--------|---------|------|--------|');

  for (const server of servers) {
    const command = `\`${truncate(server.command, 30)}\``;
    const type = server.type ?? 'stdio';
    const status = server.disabled ? 'Disabled' : 'Enabled';
    lines.push(`| **${server.name}** | ${command} | ${type} | ${status} |`);
  }

  lines.push('');

  for (const server of servers) {
    lines.push(`### ${server.name}`);
    lines.push('');

    const statusIcon = server.disabled ? '🔴' : '🟢';
    lines.push(`**Status**: ${statusIcon} ${server.disabled ? 'Disabled' : 'Enabled'}`);
    lines.push('');

    lines.push('**Command**:');
    lines.push('```bash');
    lines.push(`${server.command}${server.args?.length ? ' ' + server.args.join(' ') : ''}`);
    lines.push('```');
    lines.push('');

    if (server.env && Object.keys(server.env).length > 0) {
      lines.push('**Environment Variables**:');
      for (const [key, value] of Object.entries(server.env)) {
        // Mask sensitive values
        const displayValue = key.toLowerCase().includes('key') ||
          key.toLowerCase().includes('secret') ||
          key.toLowerCase().includes('token')
          ? '***masked***'
          : value;
        lines.push(`- \`${key}\`: \`${displayValue}\``);
      }
      lines.push('');
    }

    if (server.tools && server.tools.length > 0) {
      lines.push('**Provides Tools**:');
      for (const tool of server.tools) {
        lines.push(`- \`${tool}\``);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate metadata section
 */
function generateMetadataSection(config: AgentScopeConfig): string {
  const lines: string[] = [];
  const { metadata } = config;

  lines.push('| Property | Value |');
  lines.push('|----------|-------|');
  lines.push(`| Scanned At | ${metadata.scannedAt.toISOString()} |`);
  lines.push(`| Root Path | \`${metadata.rootPath}\` |`);
  lines.push(`| Files Scanned | ${metadata.filesScanned} |`);
  lines.push(`| Duration | ${metadata.duration}ms |`);
  lines.push(`| AgentScope Version | ${metadata.version} |`);

  if (metadata.errors.length > 0) {
    lines.push('');
    lines.push('### Scan Warnings');
    lines.push('');

    for (const error of metadata.errors) {
      const icon = error.severity === 'fatal' ? '🔴' : error.severity === 'warning' ? '🟡' : '🔵';
      lines.push(`- ${icon} **${error.code}**: ${error.message}`);
      if (error.file) {
        lines.push(`  - File: \`${error.file}\``);
      }
    }
  }

  return lines.join('\n');
}

// ============================================================================
// Helper Functions
// ============================================================================

function countAgentTypes(agents: Agent[]): Record<string, number> {
  const counts: Record<string, number> = {
    coordinator: 0,
    specialist: 0,
    reviewer: 0,
    worker: 0,
    custom: 0,
  };

  for (const agent of agents) {
    const type = agent.type ?? 'worker';
    counts[type] = (counts[type] ?? 0) + 1;
  }

  return counts;
}

function getTypeBadge(type: Agent['type']): string {
  switch (type) {
    case 'coordinator':
      return '`Coordinator`';
    case 'specialist':
      return '`Specialist`';
    case 'reviewer':
      return '`Reviewer`';
    case 'worker':
      return '`Worker`';
    default:
      return '`Custom`';
  }
}

function getHookEventDescription(event: string): string {
  const descriptions: Record<string, string> = {
    PreToolUse: 'Triggered before a tool is executed. Can modify or block tool usage.',
    PostToolUse: 'Triggered after a tool completes. Can inspect results.',
    UserPromptSubmit: 'Triggered when the user submits a prompt. Can preprocess input.',
    Notification: 'Triggered for notifications and alerts.',
    Stop: 'Triggered when the main agent stops.',
    SubagentStop: 'Triggered when a subagent stops.',
  };

  return descriptions[event] ?? 'Custom hook event.';
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function truncate(str: string, maxLength: number): string {
  if (str.length <= maxLength) return str;
  return str.slice(0, maxLength - 3) + '...';
}
