/**
 * Markdown renderer
 * Generates GitHub-flavored Markdown documentation
 */

import { Renderer, Documentation, SectionType } from '../domain/documentation/entities.js';
import { SourceAnalysis, Symbol, SymbolKind } from '../domain/source-analysis/entities.js';

export class MarkdownRenderer implements Renderer {
  render(doc: Documentation): string {
    const sections = doc.getSections();
    const parts: string[] = [];

    // Title
    const summarySection = sections.find((s) => s.type === SectionType.Summary);
    if (summarySection) {
      parts.push(`# ${summarySection.title}\n`);
      parts.push(`${summarySection.content}\n`);
    }

    // Description
    const descSection = sections.find((s) => s.type === SectionType.Description);
    if (descSection) {
      parts.push(`## Description\n\n${descSection.content}\n`);
    }

    // Other sections in order
    for (const section of sections) {
      if (section.type === SectionType.Summary || section.type === SectionType.Description) {
        continue;
      }

      parts.push(`## ${section.title}\n\n${section.content}\n`);
    }

    // Metadata footer
    parts.push(`---\n\n`);
    parts.push(`*Generated by API Reference System v${doc.metadata.version}*\n`);
    parts.push(`*Generated at: ${doc.metadata.generatedAt.toISOString()}*\n`);

    return parts.join('\n');
  }

  /**
   * Render symbol documentation
   */
  renderSymbol(symbol: Symbol): string {
    const parts: string[] = [];

    // Symbol name and kind
    parts.push(`# ${symbol.name}\n`);
    parts.push(`**Type:** ${symbol.kind}\n\n`);

    if (!symbol.tsDocComment) {
      parts.push(`*No documentation available*\n`);
      return parts.join('\n');
    }

    const doc = symbol.tsDocComment;

    // Summary
    if (doc.summary) {
      parts.push(`${doc.summary}\n`);
    }

    // Deprecated notice
    if (doc.deprecated) {
      parts.push(`\n> **⚠️ Deprecated:** ${doc.deprecated}\n`);
    }

    // Description
    if (doc.description) {
      parts.push(`\n## Description\n\n${doc.description}\n`);
    }

    // Type parameters
    if (symbol.typeParameters.length > 0) {
      parts.push(`\n## Type Parameters\n\n`);
      for (const tp of symbol.typeParameters) {
        parts.push(`- \`${tp.name}\``);
        if (tp.constraint) {
          parts.push(` extends \`${tp.constraint}\``);
        }
        if (tp.default) {
          parts.push(` = \`${tp.default}\``);
        }
        parts.push(`\n`);
      }
    }

    // Parameters
    if (doc.parameters.length > 0) {
      parts.push(`\n## Parameters\n\n`);
      parts.push(`| Name | Type | Description | Optional | Default |\n`);
      parts.push(`|------|------|-------------|----------|----------|\n`);

      for (const param of doc.parameters) {
        const opt = param.optional ? '✓' : '';
        const def = param.defaultValue || '';
        parts.push(
          `| \`${param.name}\` | \`${param.type}\` | ${param.description} | ${opt} | \`${def}\` |\n`
        );
      }
    }

    // Returns
    if (doc.returns) {
      parts.push(`\n## Returns\n\n`);
      parts.push(`**Type:** \`${doc.returns.type}\`\n\n`);
      parts.push(`${doc.returns.description}\n`);
    }

    // Examples
    if (doc.examples.length > 0) {
      parts.push(`\n## Examples\n\n`);
      for (const example of doc.examples) {
        if (example.caption) {
          parts.push(`### ${example.caption}\n\n`);
        }
        parts.push(`\`\`\`${example.language}\n${example.code}\n\`\`\`\n\n`);
      }
    }

    // Throws
    if (doc.throws.length > 0) {
      parts.push(`\n## Throws\n\n`);
      for (const throwsClause of doc.throws) {
        parts.push(`- \`${throwsClause.type}\`: ${throwsClause.description}\n`);
      }
    }

    // See Also
    if (doc.seeAlso && doc.seeAlso.length > 0) {
      parts.push(`\n## See Also\n\n`);
      for (const ref of doc.seeAlso) {
        parts.push(`- ${ref}\n`);
      }
    }

    // Since
    if (doc.since) {
      parts.push(`\n**Since:** ${doc.since}\n`);
    }

    // Declaration location
    parts.push(`\n---\n\n`);
    parts.push(`**Source:** ${symbol.declaration.filePath.toString()}:${symbol.declaration.line}\n`);

    return parts.join('');
  }

  /**
   * Render package documentation
   */
  renderPackage(analysis: SourceAnalysis): string {
    const parts: string[] = [];

    // Package header
    parts.push(`# ${analysis.packageName.toString()}\n\n`);
    parts.push(`**Version:** ${analysis.version.toString()}\n\n`);

    // Coverage stats
    const coverage = analysis.getDocumentationCoverage();
    const coveragePercent = (coverage * 100).toFixed(1);
    parts.push(`**Documentation Coverage:** ${coveragePercent}%\n\n`);

    // Table of contents
    const symbols = analysis.getPublicSymbols();
    const symbolsByKind = this.groupSymbolsByKind(symbols);

    parts.push(`## Table of Contents\n\n`);

    for (const [kind, syms] of Object.entries(symbolsByKind)) {
      if (syms.length === 0) continue;
      parts.push(`### ${kind}s\n\n`);
      for (const sym of syms) {
        parts.push(`- [${sym.name}](#${this.slugify(sym.name)})\n`);
      }
      parts.push(`\n`);
    }

    // Symbol documentation
    for (const [kind, syms] of Object.entries(symbolsByKind)) {
      if (syms.length === 0) continue;
      parts.push(`## ${kind}s\n\n`);

      for (const sym of syms) {
        parts.push(this.renderSymbol(sym));
        parts.push(`\n---\n\n`);
      }
    }

    return parts.join('');
  }

  /**
   * Group symbols by kind
   */
  private groupSymbolsByKind(symbols: Symbol[]): Record<string, Symbol[]> {
    const groups: Record<string, Symbol[]> = {
      Class: [],
      Interface: [],
      Function: [],
      Type: [],
      Enum: [],
      Variable: [],
    };

    for (const symbol of symbols) {
      const kindKey = symbol.kind.charAt(0).toUpperCase() + symbol.kind.slice(1);
      if (groups[kindKey]) {
        groups[kindKey].push(symbol);
      }
    }

    return groups;
  }

  /**
   * Create URL slug from text
   */
  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }
}
